# Generated by Django 4.2.3 on 2023-07-17 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.UUIDField()),
                ('course_details', models.JSONField()),
                ('is_purchased', models.BooleanField()),
                ('purchased_course_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubModules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_module_details', models.JSONField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_details', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.courses')),
            ],
        ),
    ]
