# Generated by Django 4.2.3 on 2023-07-16 14:43

import django.contrib.auth.models
import django.contrib.auth.password_validation
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.contrib.auth.password_validation.MinimumLengthValidator])),
                ('is_admin', models.BooleanField()),
                ('is_common_user', models.BooleanField()),
                ('is_org_user', models.BooleanField()),
                ('organization', models.UUIDField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrgDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=150, unique=True)),
                ('db_host', models.CharField(max_length=50)),
                ('db_user', models.CharField(max_length=150)),
                ('db_password', models.CharField(max_length=150)),
                ('db_port', models.PositiveIntegerField()),
                ('admin_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customusermodel')),
            ],
        ),
    ]
