# Generated by Django 4.2.3 on 2023-07-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customusermodel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='organization',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
